name: Deploy prod

on:
  push:
    branches:
      - master

jobs:

  deploy:
    name: Deploy
    uses: ./.github/workflows/deploy-shared.yml
    secrets:
      dockerUser: ${{ secrets.DOCKER_USER }}
      dockerPassword: ${{ secrets.DOCKER_PASSWORD }}
      awsAccessKey: ${{ secrets.AWS_ACCESS_KEY }}
      awsSecretKey: ${{ secrets.AWS_SECRET_KEY }}

